version: '3'

name: weather-service

services:
    API:
        image: 'weather:latest'
        ports:
            - "8081:8081"
        depends_on:
            - db
            - cache
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=weather_user
            - DB_USER=user
            - DB_PASSWORD=12345
            - SERVER_PORT=8081
            - REDIS_HOST=cache
            - REDIS_PORT=6379
    db:
        image: postgres:14
        ports:
          - "5433:5432"
        environment:
             POSTGRES_DB: weather_user
             POSTGRES_USER: user
             POSTGRES_PASSWORD: 12345
             PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
           - pgdata:/var/lib/postgresql/data

    cache:
        image: "redis"
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
volumes:
    pgdata:



