version: '3'
services:
    API:
        image: 'weather:latest'
        ports:
            - "8080:8080"
        depends_on:
            - db
            - cache
        environment:
             SPRING_PROFILES_ACTIVE : server
    db:
        image: postgres:14
        ports:
          - "5432:5432"
        environment:
             POSTGRES_DB: weather_user
             POSTGRES_USER: user
             POSTGRES_PASSWORD: 12345
             PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
           - pgdata:/var/lib/postgresql/data

    cache:
        image: "redis"
        ports:
            - "6379:6379"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
volumes:
    pgdata:



